<a href="https://colab.research.google.com/github/Alriyan1/Data_Visualization_Tutorial/blob/main/data_accessing_and_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [146]:
import pandas as pd
import numpy as np

In [147]:
patients = pd.read_csv('patients.csv')
treatments = pd.read_csv('treatments.csv')
adverse_reactions = pd.read_csv('adverse_reactions.csv')
treatments_cut= pd.read_csv('treatments_cut.csv')

In [148]:
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [149]:
treatments.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [150]:
treatments_cut.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38

In [151]:
adverse_reactions.head()

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort
1       lena        baer               hypoglycemia
2     joseph         day               hypoglycemia
3     flavia  fiorentino                      cough
4    manouck     wubbels          throat irritation

In [152]:
with pd.ExcelWriter('clinical_trails.xlsx') as writer:
    patients.to_excel(writer, sheet_name='patients')
    treatments.to_excel(writer, sheet_name='treatments')
    treatments_cut.to_excel(writer, sheet_name='treatments_cut')
    adverse_reactions.to_excel(writer, sheet_name='adverse_reactions')

In [153]:
patients.sample(5)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
270,271,female,Jowita,Wiśniewska,2168 Butternut Lane,Granite City,Illinois,62040.0,United States,JowitaWisniewska@armyspy.com+1 (618) 512-3319,11/8/1934,108.1,61,20.4
5,6,male,Rafael,Costa,1140 Willis Avenue,Daytona Beach,Florida,32114.0,United States,386-334-5237RafaelCardosoCosta@gustr.com,8/31/1931,183.9,70,26.4
117,118,male,Sửu,Tạ,3464 Big Indian,New Orleans,LA,70112.0,United States,TaQuiSuu@teleworm.us+1 (504) 528-8317,5/24/1928,182.2,67,28.5
281,282,male,Kristján,Ingason,677 Broad Street,Birmingham,AL,35203.0,United States,205-494-6040KristjanIngason@gustr.com,12/1/1986,214.1,69,31.6

In [154]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object
 9   contact       491 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 55.1+ KB

In [155]:
patients[patients['address'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [156]:
treatments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [157]:
treatments_cut.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     object
 1   surname       70 non-null     object
 2   auralin       70 non-null     object
 3   novodra       70 non-null     object
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  42 non-null     float64
dtypes: float64(3), object(4)
memory usage: 4.0+ KB

In [158]:
adverse_reactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        34 non-null     object
 1   surname           34 non-null     object
 2   adverse_reaction  34 non-null     object
dtypes: object(3)
memory usage: 944.0+ bytes

In [159]:
patients.duplicated().sum()

0

In [160]:
patients.duplicated(subset=['given_name','surname']).sum()

5

In [161]:
patients[patients.duplicated(subset=['given_name','surname'])==True]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4

In [162]:
treatments[treatments.duplicated()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [163]:
treatments[treatments.duplicated(subset=['given_name','surname'])]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [164]:
treatments_cut[treatments_cut.duplicated(subset=['given_name','surname'])]

Empty DataFrame
Columns: [given_name, surname, auralin, novodra, hba1c_start, hba1c_end, hba1c_change]
Index: []

In [165]:
adverse_reactions.duplicated().sum()

0

In [166]:
adverse_reactions.duplicated(subset=['given_name','surname']).sum()

0

In [167]:
patients.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [168]:
patients[patients['weight']==48.800000]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691.0,United States,330-202-2145CamillaZaitseva@superrito.com,11/26/1938,48.8,63,19.1

In [169]:
patients[patients['height']==27.000000]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [170]:
treatments.describe()

       hba1c_start   hba1c_end  hba1c_change
count   280.000000  280.000000    171.000000
mean      7.985929    7.589286      0.546023
std       0.568638    0.569672      0.279555
min       7.500000    7.010000      0.200000
25%       7.660000    7.270000      0.340000
50%       7.800000    7.420000      0.380000
75%       7.970000    7.570000      0.920000
max       9.950000    9.580000      0.990000

In [171]:
treatments.sort_values('hba1c_change',na_position='first')

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
8,saber,ménard,-,54u - 54u,8.08,7.70,NaN
9,asia,woźniak,30u - 36u,-,7.76,7.37,NaN
10,joseph,day,29u - 36u,-,7.70,7.19,NaN
...,...,...,...,...,...,...,...
49,jackson,addison,-,42u - 42u,7.99,7.51,0.98
17,gina,cain,-,36u - 36u,7.88,7.40,0.98
32,laura,ehrlichmann,-,43u - 40u,7.95,7.46,0.99
245,wu,sung,-,47u - 48u,7.61,7.12,0.99
138,giovana,rocha,-,23u - 21u,7.87,7.38,0.99

### Issues with the dataset

1. Dirty data

  Table - `Patients`

    - patient_id =9 has misspleded `dsvid` instead of `david` - `accuracy` ✅
    - state col sometime contain abbrivietation and some time full name - `consistency`
    - zip code col has entries with 4 digit - `validity` ✅
    - data missing for 12 patients in `address`, `city`, `state`, `zip_code`, `country`, `contact` - `completion` ✅
    - incorrect data type assigned to sex, zip code, birthdate - `validity`
    - duplicate entries by the name of John Doe - `accuracy`✅
    - one patient has weight is 48 pound - `accuracy`
    - one patient has height is 27 inches - `accuracy`
  
  Table - `Treatments` & `Treatments_cut`
    - given_name and surname col is in all lower case - `consistency`
    - remove `u` from auralin and novodra cols - `validity` ✅
    - `-` in novodra and auralin col treatment as nan - `validity` ✅
    - missing values in hba1c_change col - `completion` ✅
    - 1 duplicate entry by the name joseph day - `accuracy`
    - in hba1c_change 9 instead of 4 - `accuracy` ✅

  Table - `Adverse_reaction`
    - given_name and surname col is in all lower case - `consistency`
    
2. Messy data

  Table - `Patients`
    - contact col contain both contact and email ✅

  Table - `Treatments` & `Treatments_cut`
    - Auralin and novodra col should be split into 2 cols start and end dose ✅
    - merge both the table ✅
  
  Table - `Adverse_reaction`
    - this table should not exist independently ✅

## order of severity
- completeness > tidiness > validity > accuracy > consistency

 always make copy of original data before data cleaning

In [172]:
patients_df=patients.copy()
treatments_df=treatments.copy()
treatments_cut_df=treatments_cut.copy()
adverse_reactions_df=adverse_reactions.copy()

# Define
- replace all missing values of patients df with no data
- subtract hba1c_start from hba1c_end to all the hba1c_change
- in patients table we will use regex to separate email and phone

In [173]:
patients_df[patients['address'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [174]:
# code
patients_df.fillna('No data',inplace=True)

<ipython-input-174-432596ff9db6>:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'No data' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  patients_df.fillna('No data',inplace=True)

In [175]:
# test
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       503 non-null    object
 5   city          503 non-null    object
 6   state         503 non-null    object
 7   zip_code      503 non-null    object
 8   country       503 non-null    object
 9   contact       503 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(2), int64(2), object(10)
memory usage: 55.1+ KB

In [176]:
treatments_df.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [177]:
# code
treatments_df['hba1c_change']=treatments_df['hba1c_start']-treatments_df['hba1c_end']
treatments_cut_df['hba1c_change']=treatments_cut_df['hba1c_start']-treatments_cut_df['hba1c_end']

In [178]:
treatments_cut_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     object
 1   surname       70 non-null     object
 2   auralin       70 non-null     object
 3   novodra       70 non-null     object
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  70 non-null     float64
dtypes: float64(3), object(4)
memory usage: 4.0+ KB

In [179]:
import re
def find_contact_details(text: str) -> tuple:
    # it the value is NaN, then return it
    if pd.isna(text):
        return np.nan

    # create the phone number pattern
    phone_number_pattern = re.compile(r"(\+[\d]{1,3}\s)?(\(?[\d]{3}\)?\s?-?[\d]{3}\s?-?[\d]{4})")
    # find the phone number from the value/text, as a result we will get a list
    phone_number  = re.findall(phone_number_pattern, text)

    # if length is 0, then the regex can't find any ph number, then define with NaN
    if len(phone_number) <= 0:
        phone_number = np.nan
    # if the country code is attached with the ph number, for that case, the first
    # element will be the country code and the 2nd element will be the actual ph
    # number. So, get that ph number
    elif len(phone_number) >= 2:
        phone_number = phone_number[1]
    # else, we will get the ph number. Grab it.
    else:
        phone_number = phone_number[0]

    # if we found the ph number (with/without country code), then remove that part from the actual value.
    # after removing the ph number, the remaining string might be the email address.
    possible_email_add = re.sub(phone_number_pattern, "", text).strip()

    # then return the ph number and the email address
    return phone_number, possible_email_add

In [180]:
patients_df['phone']=patients_df['contact'].apply(lambda x: find_contact_details(x)).apply(lambda x:x[0])
patients_df['email']=patients_df['contact'].apply(lambda x: find_contact_details(x)).apply(lambda x:x[1])

In [181]:
patients_df.drop(columns='contact',inplace=True)

In [182]:
patients_df.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone,email
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,7/10/1976,121.7,66,19.6,"(, 951-719-9170)",ZoeWellish@superrito.com
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,4/3/1967,118.8,66,19.2,"(+1 , (217) 569-3204)",PamelaSHill@cuvox.de
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,2/19/1980,177.8,71,24.8,"(, 402-363-6804)",JaeMDebord@gustr.com
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,7/26/1951,220.9,70,31.7,"(+1 , (732) 636-8246)",PhanBaLiem@jourrapide.com
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,2/18/1928,192.3,27,26.1,"(, 334-515-7487)",TimNeudorf@cuvox.de

In [183]:
treatments_df=pd.concat([treatments_df,treatments_cut_df])

In [184]:
treatments_df

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
65,rovzan,kishiev,32u - 37u,-,7.75,7.41,0.34
66,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.45
67,bernd,schneider,48u - 56u,-,7.74,7.44,0.30
68,berta,napolitani,-,42u - 44u,7.68,7.21,0.47
69,armina,sauvé,36u - 46u,-,7.86,7.40,0.46

In [185]:
treatments_df=treatments_df.melt(id_vars=['given_name','surname','hba1c_start','hba1c_end','hba1c_change'],var_name='type',value_name='dosage_range')

In [186]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_range
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u - 48u
1,elliot,richardson,7.56,7.09,0.47,auralin,-
2,yukitaka,takenaka,7.68,7.25,0.43,auralin,-
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u
4,alissa,montez,7.78,7.46,0.32,auralin,-
...,...,...,...,...,...,...,...
695,rovzan,kishiev,7.75,7.41,0.34,novodra,-
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u - 26u
697,bernd,schneider,7.74,7.44,0.30,novodra,-
698,berta,napolitani,7.68,7.21,0.47,novodra,42u - 44u
699,armina,sauvé,7.86,7.40,0.46,novodra,-

In [188]:
treatments_df=treatments_df[treatments_df['dosage_range']!='-']

In [189]:
treatments_df['dosage_start']=treatments_df['dosage_range'].str.split('-').str.get(0)
treatments_df['dosage_end']=treatments_df['dosage_range'].str.split('-').str.get(1)

<ipython-input-189-eb0fa3a25ba9>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_start']=treatments_df['dosage_range'].str.split('-').str.get(0)
<ipython-input-189-eb0fa3a25ba9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_end']=treatments_df['dosage_range'].str.split('-').str.get(1)

In [190]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_range,dosage_start,dosage_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u - 48u,41u,48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u,33u,36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u - 42u,37u,42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u - 38u,31u,38u
9,asia,woźniak,7.76,7.37,0.39,auralin,30u - 36u,30u,36u
...,...,...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55u - 51u,55u,51u
690,maret,sultygov,7.67,7.30,0.37,novodra,26u - 23u,26u,23u
694,lixue,hsueh,9.21,8.80,0.41,novodra,22u - 23u,22u,23u
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u - 26u,28u,26u
698,berta,napolitani,7.68,7.21,0.47,novodra,42u - 44u,42u,44u

In [191]:
treatments_df.drop(columns='dosage_range',inplace=True)

<ipython-input-191-a85ce73783c4>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df.drop(columns='dosage_range',inplace=True)

In [192]:
treatments_df.head()

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u,48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u,36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u,42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u,38u
9,asia,woźniak,7.76,7.37,0.39,auralin,30u,36u

In [195]:
treatments_df['dosage_start']=treatments_df['dosage_start'].str.replace('u','')
treatments_df['dosage_end']=treatments_df['dosage_end'].str.replace('u','')

<ipython-input-195-5b60359396f2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_start']=treatments_df['dosage_start'].str.replace('u','')
<ipython-input-195-5b60359396f2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_end']=treatments_df['dosage_end'].str.replace('u','')

In [196]:
treatments_df.head()

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48
3,skye,gormanston,7.97,7.62,0.35,auralin,33,36
6,sophia,haugen,7.65,7.27,0.38,auralin,37,42
7,eddie,archer,7.89,7.55,0.34,auralin,31,38
9,asia,woźniak,7.76,7.37,0.39,auralin,30,36

In [197]:
treatments_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 350 entries, 0 to 698
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    350 non-null    object
 1   surname       350 non-null    object
 2   hba1c_start   350 non-null    float64
 3   hba1c_end     350 non-null    float64
 4   hba1c_change  350 non-null    float64
 5   type          350 non-null    object
 6   dosage_start  350 non-null    object
 7   dosage_end    350 non-null    object
dtypes: float64(3), object(5)
memory usage: 24.6+ KB

In [200]:
treatments_df['dosage_start']=treatments_df['dosage_start'].astype('int')
treatments_df['dosage_end']=treatments_df['dosage_end'].astype('int')

<ipython-input-200-40078f04ed3e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_start']=treatments_df['dosage_start'].astype('int')
<ipython-input-200-40078f04ed3e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_end']=treatments_df['dosage_end'].astype('int')

In [201]:
treatments_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 350 entries, 0 to 698
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    350 non-null    object
 1   surname       350 non-null    object
 2   hba1c_start   350 non-null    float64
 3   hba1c_end     350 non-null    float64
 4   hba1c_change  350 non-null    float64
 5   type          350 non-null    object
 6   dosage_start  350 non-null    int64
 7   dosage_end    350 non-null    int64
dtypes: float64(3), int64(2), object(3)
memory usage: 24.6+ KB

In [203]:
treatments_df=treatments_df.merge(adverse_reactions_df,how='left',on=['given_name','surname'])

In [204]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48,NaN
1,skye,gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,sophia,haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,eddie,archer,7.89,7.55,0.34,auralin,31,38,NaN
4,asia,woźniak,7.76,7.37,0.39,auralin,30,36,NaN
...,...,...,...,...,...,...,...,...,...
345,christopher,woodward,7.51,7.06,0.45,novodra,55,51,nausea
346,maret,sultygov,7.67,7.30,0.37,novodra,26,23,NaN
347,lixue,hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
348,jakob,jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
349,berta,napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort

In [222]:
patients_df[patients['zip_code'].apply(lambda x:len(str(x)))==6]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone,email
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,7/26/1951,220.9,70,31.7,"(+1 , (732) 636-8246)",PhanBaLiem@jourrapide.com
20,21,female,Sofia,Karlsen,2931 Romano Street,Whitman,MA,2382.0,United States,9/24/1934,153.1,66,24.7,"(, 781 447 1763)",SofiaTKarlsen@teleworm.us1
34,35,female,Mariana,Souza,577 Chipmunk Lane,Orrington,ME,4474.0,United States,3/6/1948,152.9,63,27.1,"(, 207-825-8634)",MarianaGomesSouza@superrito.com
38,39,female,Genet,Fesahaye,4649 Joanne Lane,Westborough,MA,1581.0,United States,1/11/1954,111.8,67,17.5,"(, 978 460 9060)",GenetFesahaye@armyspy.com1
39,40,female,Ganimete,Ščančar,4105 Ferguson Street,Walpole,MA,2081.0,United States,10/25/1947,191.6,67,30.0,"(, 508-454-2027)",GanimeteScancar@cuvox.de
44,45,female,Blanka,Jurković,3165 Upton Avenue,Waterville,ME,4901.0,United States,1/26/1923,129.8,66,20.9,"(, 207 861 4587)",BlankaJurkovic@superrito.com1
53,54,male,Kwemtochukwu,Ogochukwu,2172 Lynn Street,Franklin,MA,2038.0,United States,6/30/1976,150.5,72,20.4,"(, 617-317-5055)",KwemtochukwuOgochukwu@einrot.com
54,55,female,Louise,Johnson,4984 Hampton Meadows,Burlington,MA,1803.0,United States,3/1/1931,141.0,62,25.8,"(, 978-407-1874)",LouiseJohnson@rhyta.com
62,63,female,Firenze,Fodor,1786 Gerald L. Bates Drive,Belmont,MA,2178.0,United States,4/1/1943,131.1,60,25.6,"(, 617-883-5967)",FodorFirenze@dayrep.com
67,68,male,Nebechi,Ekechukwu,2418 Smith Street,Marlboro,MA,1752.0,United States,1/11/1945,154.9,64,26.6,"(, 508-804-4850)",NebechiEkechukwu@teleworm.us
71,72,male,Leuco,Miranda,90 Meadow View Drive,Hartford,CT,6103.0,United States,2/2/1976,184.8,72,25.1,"(, 860-515-0122)",LeucoMirandaNieto@teleworm.us
73,74,female,Žarka,Rap,2661 Russell Street,Foxboro,MA,2035.0,United States,12/28/1995,139.3,68,21.2,"(, 978-969-6753)",ZarkaRap@superrito.com
78,79,female,Fauna,Bilodeau,4104 Kennedy Court,Mansfield,MA,2048.0,United States,7/2/1979,193.4,69,28.6,"(, 774 263 5317)",FaunaBilodeau@teleworm.us1
92,93,male,Michael,Smith,666 Whiteman Street,Mount Holly,NJ,8060.0,United States,9/17/1977,160.6,67,25.2,"(, 609-914-8473)",MichaelSmith@armyspy.com
96,97,female,Nasim,Salib,3161 Fantages Way,Presque Isle,ME,4769.0,United States,7/30/1971,211.4,65,35.2,"(, 207-768-0477)",NasimSumaiyaSalib@einrot.com
124,125,male,Ming,Hsu,2945 Ferguson Street,Quincy,MA,2169.0,United States,11/4/1960,215.6,69,31.8,"(+1 , (508) 526-3432)",MingHsu@armyspy.com
126,127,male,Mads,Nielsen,1493 Randolph Street,Boston,MA,2210.0,United States,5/19/1942,137.1,68,20.8,"(, 508-739-5632)",MadsANielsen@jourrapide.com
167,168,female,Melisa,Mata,2775 Single Street,Bedford,MA,1730.0,United States,12/15/1941,209.7,65,34.9,"(, 781-604-1901)",MelisaMataSantacruz@rhyta.com
176,177,female,Makda,Abraham,4093 Smith Street,Lowell,MA,1852.0,United States,6/24/1979,145.2,65,24.2,"(, 508 857 0477)",MakdaAbraham@einrot.com1
182,183,male,Kaodilinakachukwu,Nnonso,3261 Desert Broom Court,Jersey City,NJ,7304.0,United States,11/9/1963,230.3,69,34.0,"(, 201-739-3931)",KaodilinakachukwuNnonso@gustr.com
186,187,female,Jane,Citizen,2866 Myra Street,Providence,RI,2908.0,United States,9/27/1974,143.0,65,23.8,"(+1 , (401) 485-6384)",JaneCitizen@cuvox.de
193,194,male,Borna,Šlezinger,3073 Bedford Street,West Haven,CT,6516.0,United States,3/21/1987,203.9,69,30.1,"(, 203-933-3979)",BornaSlezinger@cuvox.de
194,195,male,Urso,Aranda,1330 Lincoln Street,Hopewell Mercer,NJ,8525.0,United States,7/3/1999,163.7,70,23.5,"(, 609-466-3275)",UrsoArandaSanchez@rhyta.com
200,201,male,Kifle,Mustafa,4535 Prospect Street,Pennsauken,NJ,8110.0,United States,10/9/1965,186.1,69,27.5,"(, 856-655-5415)",KifleMustafa@gustr.com
201,202,male,Pirro,Galvez,2831 Milford Street,Exeter,NH,3833.0,United States,2/25/1971,172.5,73,22.8,"(, 603 773 2333)",PirroGalvezPaz@armyspy.com1
214,215,female,Gabriela,Michalčíková,383 Marion Street,Hartford,VT,5047.0,United States,10/8/1964,126.9,65,21.1,"(+1 , (802) 952-6490)",GabrielaMichalcikova@rhyta.com
224,225,female,Veronika,Jindrová,3641 Selah Way,Brattleboro,VT,5301.0,United States,1/15/1981,171.4,62,31.3,"(, 802-614-0812)",VeronikaJindrova@jourrapide.com
252,253,male,Juan,Pérez,2549 Pearlman Avenue,Bedford,MA,1730.0,United States,10/1/1991,224.2,70,32.2,"(, 978-243-8596)",JuanPerez@teleworm.us
261,262,male,Jeremy,Montagu,4988 Lynn Street,Boston,MA,2110.0,United States,6/23/1982,192.7,74,24.7,"(, 617-297-0387)",JeremyMontagu@teleworm.us
284,285,male,Nilton,Quintanilla,4038 Farland Street,Walpole,MA,2081.0,United States,2/9/1980,186.3,75,23.3,"(, 774-219-3140)",NiltonQuintanillaAlmonte@rhyta.com
290,291,female,Una,Traustadóttir,1027 Tenmile Road,Bedford,MA,1730.0,United States,2/1/1930,152.3,59,30.8,"(, 781-739-0244)",UnaTraustadottir@armyspy.com
294,295,female,Annie,Allen,3634 Lyon Avenue,Cambridge,MA,2142.0,United States,3/31/1926,159.7,60,31.2,"(, 508 921 6327)",AnnieJAllen@superrito.com1
314,315,male,Renzo,Lucchese,4145 Fairfax Drive,Branchburg,NJ,8876.0,United States,2/5/1970,212.1,69,31.3,"(, 908-884-4247)",RenzoLucchese@dayrep.com
316,317,female,Chân,Bùi,115 Frank Avenue,Amherst,MA,1002.0,United States,10/11/1932,162.1,61,30.6,"(, 413-259-3637)",BuiQuynhChan@fleckens.hu
327,328,male,Torfi,Írisarson,1463 Beechwood Avenue,Belleville,NJ,7109.0,United States,10/3/1977,214.7,68,32.6,"(, 908-871-7009)",TorfiIrisarson@jourrapide.com
342,343,female,Mathilde,Nørgaard,846 Copperhead Road,Hartford,CT,6182.0,United States,1/21/1985,127.2,61,24.0,"(, 860 618 4560)",MathildeDNrgaard@superrito.com1
343,344,female,Emy,Markus,288 Colony Street,Stamford,CT,6901.0,United States,1/30/1999,140.6,65,23.4,"(, 203-251-3573)",EmyMarkus@armyspy.com
354,355,female,Vivian,House,4932 Goldleaf Lane,Newark,NJ,7102.0,United States,8/13/1936,130.2,62,23.8,"(, 201-586-2848)",VivianRHouse@dayrep.com
355,356,female,Chiho,Higa,4500 Myra Street,Providence,RI,2905.0,United States,5/25/1935,182.6,59,36.9,"(, 401-456-2797)",ChihoHiga@teleworm.us
358,359,female,Amalie,Christensen,3077 Colony Street,Meriden,CT,6450.0,United States,10/1/1941,160.8,63,28.5,"(, 203 235 1076)",AmalieJChristensen@einrot.com1
368,369,male,Corey,Nicholls,3427 Gerald L. Bates Drive,Boston,MA,2110.0,United States,4/25/1989,165.0,74,21.2,"(, 617 830 7216)",CoreyNicholls@jourrapide.com1
370,371,male,Olof,Holm,288 Smith Street,Taunton,MA,2780.0,United States,4/7/1999,214.1,70,30.7,"(, 508-821-2421)",OlofHolm@gustr.com
371,372,female,Asya,Musliyevich,1763 Williams Mine Road,Weehawken,NJ,7087.0,United States,7/15/1995,156.0,63,27.6,"(+1 , (908) 287-7099)",AsyaMusliyevich@armyspy.com
380,381,female,Silje,Kristiansen,4992 Moonlight Drive,Pleasantville,NJ,8232.0,United States,2/7/1996,162.4,64,27.9,"(, 609-641-2070)",SiljeAKristiansen@dayrep.com
403,404,male,Robert,Maslov,2356 Myra Street,Providence,RI,2908.0,United States,7/2/1932,219.1,65,36.5,"(, 401-535-2675)",RobertMaslov@fleckens.hu
424,425,female,Krystiana,Kozłowska,2935 Diamond Cove,Providence,RI,2906.0,United States,11/8/1921,123.6,63,21.9,"(+1 , (401) 419-2975)",KrystianaKozlowska@cuvox.de
425,426,female,Taylah,Mobourne,995 Beechwood Avenue,Weehawken,NJ,7087.0,United States,7/4/1961,188.5,67,29.5,"(, 908-751-4255)",TaylahMobourne@rhyta.com
473,474,female,Kate,Wilkinson,664 Lyon Avenue,South Boston,MA,2127.0,United States,7/18/1998,175.3,65,29.2,"(, 508 905 2371)",KateWilkinson@armyspy.com1
498,499,male,Mustafa,Lindström,2530 Victoria Court,Milton Mills,ME,3852.0,United States,4/10/1959,181.1,72,24.6,"(, 207-477-0579)",MustafaLindstrom@jourrapide.com

In [224]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       503 non-null    object
 5   city          503 non-null    object
 6   state         503 non-null    object
 7   zip_code      503 non-null    object
 8   country       503 non-null    object
 9   birthdate     503 non-null    object
 10  weight        503 non-null    float64
 11  height        503 non-null    int64
 12  bmi           503 non-null    float64
 13  phone         491 non-null    object
 14  email         503 non-null    object
dtypes: float64(2), int64(2), object(11)
memory usage: 59.1+ KB

In [225]:
patients_df[patients_df['phone'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone,email
209,210,female,Lalita,Eldarkhanov,No data,No data,No data,No data,No data,8/14/1950,143.4,62,26.2,NaN,No data
219,220,male,Mỹ,Quynh,No data,No data,No data,No data,No data,4/9/1978,237.8,69,35.1,NaN,No data
230,231,female,Elisabeth,Knudsen,No data,No data,No data,No data,No data,9/23/1976,165.9,63,29.4,NaN,No data
234,235,female,Martina,Tománková,No data,No data,No data,No data,No data,4/7/1936,199.5,65,33.2,NaN,No data
242,243,male,John,O'Brian,No data,No data,No data,No data,No data,2/25/1957,205.3,74,26.4,NaN,No data
249,250,male,Benjamin,Mehler,No data,No data,No data,No data,No data,10/30/1951,146.5,69,21.6,NaN,No data
257,258,male,Jin,Kung,No data,No data,No data,No data,No data,5/17/1995,231.7,69,34.2,NaN,No data
264,265,female,Wafiyyah,Asfour,No data,No data,No data,No data,No data,11/3/1989,158.6,63,28.1,NaN,No data
269,270,female,Flavia,Fiorentino,No data,No data,No data,No data,No data,10/9/1937,175.2,61,33.1,NaN,No data
278,279,female,Generosa,Cabán,No data,No data,No data,No data,No data,12/16/1962,124.3,69,18.4,NaN,No data
286,287,male,Lewis,Webb,No data,No data,No data,No data,No data,4/1/1979,155.3,68,23.6,NaN,No data
296,297,female,Chỉ,Lâm,No data,No data,No data,No data,No data,5/14/1990,181.1,63,32.1,NaN,No data

In [226]:
patients_df.fillna('No data',inplace=True)

In [228]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       503 non-null    object
 5   city          503 non-null    object
 6   state         503 non-null    object
 7   zip_code      503 non-null    object
 8   country       503 non-null    object
 9   birthdate     503 non-null    object
 10  weight        503 non-null    float64
 11  height        503 non-null    int64
 12  bmi           503 non-null    float64
 13  phone         503 non-null    object
 14  email         503 non-null    object
dtypes: float64(2), int64(2), object(11)
memory usage: 59.1+ KB

In [234]:
patients_df[patients_df['given_name']=='Dsvid']

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone,email
8,9,male,Dsvid,Gustafsson,1790 Nutter Street,Kansas City,MO,64105.0,United States,3/6/1937,163.9,66,26.5,"(, 816-265-9578)",DavidGustafsson@armyspy.com

In [235]:
patients_df['given_name'].replace({'Dsvid':'David'},inplace=True)

<ipython-input-235-8cc72503f7c6>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  patients_df['given_name'].replace({'Dsvid':'David'},inplace=True)

In [236]:
patients_df[patients_df['given_name']=='David']

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone,email
8,9,male,David,Gustafsson,1790 Nutter Street,Kansas City,MO,64105.0,United States,3/6/1937,163.9,66,26.5,"(, 816-265-9578)",DavidGustafsson@armyspy.com
280,281,male,David,Beauvais,98 Freshour Circle,San Antonio,TX,78258.0,United States,5/1/1931,128.5,67,20.1,"(, 210-218-3477)",DavidLBeauvais@rhyta.com
440,441,male,David,Villadsen,1434 Oak Ridge Drive,St Elizabeth,MO,65559.0,United States,11/30/1924,137.3,68,20.9,"(+1 , (573) 493-4748)",DavidMVilladsen@armyspy.com

In [241]:
patients_df[patients_df.duplicated(subset=['given_name','surname'])==True]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,birthdate,weight,height,bmi,phone,email
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,1/1/1975,180.0,72,24.4,"(, 1234567890)",johndoe@email.com
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,1/1/1975,180.0,72,24.4,"(, 1234567890)",johndoe@email.com
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,1/1/1975,180.0,72,24.4,"(, 1234567890)",johndoe@email.com
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,1/1/1975,180.0,72,24.4,"(, 1234567890)",johndoe@email.com
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,1/1/1975,180.0,72,24.4,"(, 1234567890)",johndoe@email.com

In [242]:
patients_df.drop_duplicates(subset=['given_name','surname'],keep='first',inplace=True)

In [243]:
patients_df.duplicated(subset=['given_name','surname']).sum()

0

In [245]:
patients_df['state'].unique()

array(['California', 'Illinois', 'Nebraska', 'NJ', 'AL', 'Florida', 'NV',
       'CA', 'MO', 'New York', 'MI', 'TN', 'VA', 'OK', 'GA', 'MT', 'MA',
       'NY', 'NM', 'IL', 'LA', 'PA', 'CO', 'ME', 'WI', 'SD', 'MN', 'FL',
       'WY', 'OH', 'IA', 'NC', 'IN', 'CT', 'KY', 'DE', 'MD', 'AZ', 'TX',
       'NE', 'AK', 'ND', 'KS', 'MS', 'WA', 'SC', 'WV', 'RI', 'NH', 'OR',
       'No data', 'VT', 'ID', 'DC', 'AR'], dtype=object)

In [246]:
patients_df['city'].unique()

array(['Rancho California', 'Armstrong', 'York', 'Woodbridge', 'Dothan',
       'Daytona Beach', 'Burbank', 'Morgan Hill', 'Kansas City',
       'New York', 'Rudyard', 'Brentwood', 'Lynchburg', 'Birmingham',
       'Tulsa', 'Kingsport', 'Fresno', 'Smyrna', 'Ekalaka', 'Oroville',
       'Whitman', 'Elmsford', 'Pleasantville', 'Winter Haven',
       'Port Jervis', 'Albuquerque', 'Peoria', 'Venice',
       'Fort Washington', 'Englewood', 'Bluff City', 'Long Beach',
       'Dekalb', 'Orrington', 'Eau Claire', 'Huron', 'Westborough',
       'Walpole', 'Atlanta', 'Danube', 'West Palm Beach', 'Mountain View',
       'Waterville', 'Adamsville', 'Pittsburgh', 'Lombard', 'Maumee',
       'Wilkes Barre', 'Davenport', 'Urbandale', 'Franklin', 'Burlington',
       'Las Vegas', 'Eatonton', 'La Mesa', 'Wilson', 'San Diego',
       'Bakersfield', 'Belmont', 'Syracuse', 'Rossville', 'Marlboro',
       'Milwaukee', 'Athens', 'Hartford', 'Metairie', 'Foxboro',
       'Fremont', 'Minneapolis', 'Lexington', 'Mansfield', 'Philadelphia',
       'Westbury', 'Gate', 'Dayton', 'Kissimmee', 'Temple Hills',
       'Ogilvie', 'Augusta', 'Tempe', 'Buffalo', 'Houston', 'Mount Holly',
       'Sunrise', 'Miami', 'Blackwell', 'Presque Isle', 'Burr',
       'Fairbanks', 'Binford', 'Fordland', 'Montgomery', 'Maitland',
       'Phoenix', 'Clinton', 'New Castle', 'Mount Airy', 'Bushton',
       'Hattiesburg', 'Dallas', 'Newhall', 'Newport News', 'Manhattan',
       'Lakeport', 'Allen', 'New Orleans', 'Delcambre', 'San Francisco',
       'Grand Rapids', 'Tampa', 'Quincy', 'Boston', 'Elma',
       'Indianapolis', 'North Charleston', 'Rainelle', 'Lake Ariel',
       'Columbia', 'Albany', 'Cleveland', 'Los Angeles', 'Pompano Beach',
       'Richmond', 'Cincinnati', 'Decatur', 'Seattle', 'Fort Wayne',
       'Eagleville', 'East Chicago', 'West Los Angeles', 'Brooklyn',
       'Mountain Home', 'Dundee', 'Citrus Heights', 'Reno', 'Madison',
       'East Saint Louis', 'Roseville', 'Chilton', 'Sylva', 'Chester',
       'Sacramento', 'Winnsboro', 'Olathe', 'Yazoo City', 'Longview',
       'Bedford', 'Palo Alto', 'Bensalem', 'La Grange', 'Iowa City',
       'Auburn Hills', 'Spokane', 'Jacksonville', 'Lowell', 'Chicago',
       'Marshalltown', 'Monroe', 'Gypsum', 'Jersey City', 'Fontana',
       'Ormond Beach', 'Elkton', 'Providence', 'Gibsonia', 'Garden City',
       'West Haven', 'Hopewell  Mercer', 'Austin', 'Gaylord', 'Dora',
       'Pennsauken', 'Exeter', 'Portland', 'Harvester', 'Oklahoma City',
       'Tonawanda', 'Canadian', 'Saginaw', 'Arlington', 'No data',
       'Wooster', 'Saint Paul', 'Charlotte', 'La Follette', 'Oakland',
       'Louisville', 'Downey', 'Brattleboro', 'Washington',
       'Fairview Park', 'Omaha', 'Halifax', 'Pippa Passes', 'Aurora',
       'Gulfport', 'Huntsville', 'Superior', 'Rockford', 'Santa Ana',
       'North Loup', 'Dundalk', 'Orlando', 'Elk Lake', 'Trevorton',
       'Antioch', 'Mio', 'Whitesburg', 'Salina', 'San Carlos',
       'Granite City', 'Edinburg', 'State Line', 'Westerville', 'Hope',
       'Riverton', 'San Antonio', 'Santa Cruz', 'Kenner',
       'Camden Wyoming', 'Cissna Park', 'Walnut Creek', 'Cambridge',
       'Crafton', 'Corpus Christi', 'Bovill', 'Columbus', 'Detroit',
       'Binghamton', 'Palmyra', 'Huntington', 'Lenexa', 'Atmore',
       'Branchburg', 'Amherst', 'Fargo', 'Schenectady', 'Belleville',
       'Pritchardville', 'Irvine', 'Old Hickory', 'Monroeville',
       'Bartlett', 'Crawfordsville', 'Pontiac', 'Eagle', 'Apple Valley',
       'Palmdale', 'Fullerton', 'Stamford', 'Medaryville', 'New Glarus',
       'Packwood', 'Rylie', 'Chattanooga', 'Savannah', 'Dudley', 'Newark',
       'Maurepas', 'Bellefontaine', 'Meriden', 'Copperas Cove', 'El Paso',
       'Norfolk', 'Sherman Oaks', 'Salem', 'Aberdeen', 'Sparks',
       'Taunton', 'Weehawken', 'Collinsville', 'Springdale', 'Colfax',
       'Houma', 'Wichita', 'Tolono', 'Memphis', 'Sulphur', 'Wheatley',
       'Mount Pleasant', 'Monteview', 'Custer', 'Nellysford', 'San Jose',
       'Fort Lauderdale', 'Shreveport', 'Lemont', 'Reston', 'Tyler',
       'Yadkinville', 'Sebring', 'Scottsville', 'Cave Spring', 'Plymouth',
       'Lawrence', 'Utica', 'Texas City', 'Dalton', 'Grayling', 'Wayne',
       'Versailles', 'Diamond Bar', 'Redmond', 'Stanton', 'Little Rock',
       'Haverhill', 'Colorado Springs', 'Abilene', 'Grand Forks',
       'Devils Lake', 'Dublin', 'Anaheim', 'Union Grove',
       'New Philadelphia', 'Des Moines', 'St Elizabeth', 'San Joaquin',
       'Ocala', 'Mclain', 'Garfield Heights', 'Roslyn', 'Upland',
       'Harrisburg', 'Cumberland', 'Yardley', 'Fort Worth', 'Owensville',
       'Springville', 'Hillsboro', 'Golden Valley', 'Redding', 'Argyle',
       'Wilmington', 'Live Oak', 'Natchez', 'South Boston', 'Florence',
       'Ontario', 'Greensboro', 'Fort Walton Beach', 'Waco', 'Ottawa',
       'Lafayette', 'New Rochelle', 'Boise', 'San Mateo', 'Stockton',
       'Milton Mills', 'Sedona', 'Overland Park'], dtype=object)